# Generated by Django 3.2.5 on 2022-05-02 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeUser',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('fullname', models.CharField(default=None, max_length=20)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('address', models.CharField(default=None, max_length=150)),
                ('is_health', models.CharField(default=None, max_length=3)),
                ('health_info', models.CharField(default=None, max_length=50)),
                ('registered_as', models.CharField(default=None, max_length=10)),
                ('password', models.CharField(default=None, max_length=150)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('fullname', models.CharField(default=None, max_length=20)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('address', models.CharField(default=None, max_length=150)),
                ('is_health', models.CharField(default=None, max_length=3)),
                ('health_info', models.CharField(default=None, max_length=50)),
                ('registered_as', models.CharField(default=None, max_length=10)),
                ('password', models.CharField(default=None, max_length=150)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
