# Generated by Django 3.2.5 on 2022-05-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_medicalinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='user_email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.websiteuser', unique=True),
        ),
    ]
