# Generated by Django 4.0.3 on 2022-05-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_medicalinformation_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinformation',
            name='user_email',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.websiteuser'),
        ),
    ]
