# Generated by Django 4.0.3 on 2022-05-18 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_medicalinformation_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
