# Generated by Django 4.0.3 on 2022-05-18 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_websiteuser_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomeUser',
        ),
        migrations.AlterField(
            model_name='medicalinformation',
            name='user_email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.websiteuser'),
        ),
    ]
