# Generated by Django 4.0.3 on 2022-05-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_customeuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('fullname', models.CharField(default=None, max_length=20)),
                ('gender', models.CharField(default=None, max_length=6)),
                ('address', models.CharField(default=None, max_length=150)),
                ('is_health', models.CharField(default=None, max_length=3)),
                ('health_info', models.CharField(default=None, max_length=50)),
                ('registered_as', models.CharField(default=None, max_length=10)),
                ('password', models.CharField(default=None, max_length=150)),
                ('auth_token', models.CharField(default=None, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
