# Generated by Django 4.0.3 on 2022-05-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='auth_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
