# Generated by Django 4.0.3 on 2022-05-18 02:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customeuser_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
