# Generated by Django 4.0.3 on 2022-05-18 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_uuid_websiteuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websiteuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
