# Generated by Django 4.0.3 on 2022-05-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_customeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='id',
            field=models.CharField(default='<function uuid4 at 0x7f2cbba3a1f0>', editable=False, max_length=100, unique=True),
        ),
    ]
