# Generated by Django 4.0.3 on 2022-05-23 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_websiteuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
