# Generated by Django 4.0.3 on 2022-05-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yogas', '0020_yogaasanasequence'),
        ('users', '0007_alter_medicalinformation_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asanasequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yogas.yogaasanasequence')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.websiteuser')),
            ],
        ),
        migrations.CreateModel(
            name='YogaClassMember',
            fields=[
                ('yogaclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='classcalendar.yogaclass')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogas.yogaasanasequence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.websiteuser')),
                ('yoga_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoga_class_name', to='classcalendar.yogaclass')),
            ],
            options={
                'unique_together': {('yoga_class', 'student', 'sequence')},
            },
            bases=('classcalendar.yogaclass',),
        ),
    ]
