# Generated by Django 4.0.3 on 2022-05-15 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='attendee',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
        ),
    ]
