# Generated by Django 4.0.3 on 2022-05-16 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0003_remove_yogaclass_end_time_yogaclass_timeduration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaclass',
            name='timeduration',
        ),
        migrations.AddField(
            model_name='yogaclass',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
