# Generated by Django 4.0.3 on 2022-05-17 12:57

import classcalendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0005_alter_yogaclass_asanasequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='image_thumbnail',
            field=models.ImageField(default=None, upload_to=classcalendar.models.content_thumbfile_name),
        ),
    ]
