# Generated by Django 4.0.3 on 2022-05-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0020_yogaasanasequence'),
        ('classcalendar', '0006_yogaclass_image_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yogaclass',
            options={'ordering': ['id', 'title', 'start_time', 'end_time']},
        ),
        migrations.AlterField(
            model_name='yogaclassmember',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yogas.yogaasanasequence'),
        ),
    ]
