# Generated by Django 4.0.3 on 2022-05-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0007_alter_yogaclass_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yogaclassmember',
            unique_together=set(),
        ),
    ]
