# Generated by Django 4.0.3 on 2022-05-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0011_yogaclassandsequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaclass',
            name='asanasequence',
        ),
    ]
