# Generated by Django 4.0.3 on 2022-05-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0012_remove_yogaclass_asanasequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmember',
            name='sequence',
        ),
        migrations.DeleteModel(
            name='YogaClassAndSequence',
        ),
    ]
