# Generated by Django 3.2.5 on 2022-05-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asana_name', models.CharField(default=None, max_length=50)),
                ('asana_sanscrut_name', models.CharField(default=None, max_length=50)),
                ('asana_english_name', models.CharField(default=None, max_length=50)),
                ('asana_category', models.CharField(default=None, max_length=30)),
                ('asana_sub_category', models.CharField(default=None, max_length=30)),
                ('difficulty', models.CharField(default=None, max_length=15)),
                ('how_to_do', models.TextField(default=None, max_length=5000)),
                ('benifit', models.CharField(default=None, max_length=500)),
                ('caution', models.CharField(default=None, max_length=500)),
                ('start_position', models.CharField(default=None, max_length=100)),
                ('concentration', models.CharField(default=None, max_length=200)),
                ('breath', models.CharField(default=None, max_length=100)),
                ('repetitions', models.CharField(default=None, max_length=200)),
                ('image_thumbnail', models.FileField(null=True, upload_to='static/images/yogas')),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'ordering': ['id', 'asana_name'],
            },
        ),
        migrations.CreateModel(
            name='YogaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='static/images/Yoga')),
                ('asana', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yogas.asana')),
            ],
            options={
                'ordering': ['asana_id'],
            },
        ),
        migrations.CreateModel(
            name='AsanaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asana_large_image', models.CharField(max_length=200)),
                ('asana_small_image', models.CharField(max_length=200)),
                ('asana_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogas.asana')),
            ],
            options={
                'ordering': ['asana_id'],
            },
        ),
    ]
