# Generated by Django 3.2.5 on 2022-05-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ('position_name',),
            },
        ),
        migrations.CreateModel(
            name='YogaTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
        ),
    ]
