# Generated by Django 3.2.5 on 2022-05-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0002_yogaposition_yogatypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YogaTypes',
            new_name='YogaType',
        ),
    ]
