# Generated by Django 3.2.5 on 2022-05-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0003_rename_yogatypes_yogatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='asana',
            name='asana_position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='yogas.yogaposition'),
        ),
        migrations.AddField(
            model_name='asana',
            name='asana_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='yogas.yogatype'),
        ),
    ]
