# Generated by Django 3.2.5 on 2022-05-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0006_yogadificulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='asana',
            name='asana_difficulty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='yogas.yogadificulty'),
        ),
    ]
