# Generated by Django 3.2.5 on 2022-05-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0007_asana_asana_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asana',
            name='asana_category',
        ),
        migrations.RemoveField(
            model_name='asana',
            name='asana_sub_category',
        ),
        migrations.RemoveField(
            model_name='asana',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='asana',
            name='asana_difficulty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='yogas.yogadificulty'),
        ),
        migrations.AlterField(
            model_name='asana',
            name='asana_position',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='yogas.yogaposition'),
        ),
        migrations.AlterField(
            model_name='asana',
            name='asana_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='yogas.yogatype'),
        ),
        migrations.AlterField(
            model_name='asana',
            name='image_thumbnail',
            field=models.FileField(default=None, upload_to='static/images/yogas'),
        ),
        migrations.AlterField(
            model_name='asana',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterField(
            model_name='yogadificulty',
            name='difficulty_name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='yogaposition',
            name='position_name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
