# Generated by Django 4.0.3 on 2022-05-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0009_asana_created_by_asana_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asana',
            name='benifit',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='asana',
            name='caution',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
