# Generated by Django 4.0.3 on 2022-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0010_alter_asana_benifit_alter_asana_caution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asana',
            name='image_thumbnail',
            field=models.ImageField(default=None, upload_to='static/images/yogas'),
        ),
        migrations.AlterField(
            model_name='yogaimage',
            name='images',
            field=models.FileField(upload_to='static/images/yogas'),
        ),
    ]
