# Generated by Django 4.0.3 on 2022-05-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0011_alter_asana_image_thumbnail_alter_yogaimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaimage',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
