# Generated by Django 4.0.3 on 2022-05-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0012_alter_yogaimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asana',
            name='image_thumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
