# Generated by Django 4.0.3 on 2022-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0013_alter_asana_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asana',
            name='image_thumbnail',
            field=models.ImageField(default=None, upload_to='media/static/images/yogas'),
        ),
        migrations.AlterField(
            model_name='yogaimage',
            name='images',
            field=models.ImageField(upload_to='media/static/images/yogas'),
        ),
    ]
