# Generated by Django 4.0.3 on 2022-05-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0015_alter_asana_image_thumbnail_alter_yogaimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asana',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='yogaimage',
            name='images',
            field=models.FileField(upload_to='media/images/'),
        ),
    ]
