# Generated by Django 4.0.3 on 2022-05-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0016_alter_asana_slug_alter_yogaimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asana',
            name='image_thumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='yogaimage',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
