# Generated by Django 4.0.3 on 2022-05-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yogas', '0019_alter_asana_image_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaAsanaSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_name', models.CharField(max_length=50)),
                ('seq_asana_num', models.IntegerField(default=None)),
                ('seq_asana', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Yoga', to='yogas.asana')),
                ('seq_difficulty', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='yogas.yogadificulty')),
                ('seq_position', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='yogas.yogaposition')),
                ('seq_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='yogas.yogatype')),
            ],
            options={
                'ordering': ['id', 'seq_name'],
            },
        ),
    ]
