# Generated by Django 4.0.3 on 2022-05-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_websiteuser_created_at_websiteuser_updated_at'),
        ('yogas', '0021_alter_asana_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='favouriteAsana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='yogas.asana')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.websiteuser')),
            ],
            options={
                'unique_together': {('asan', 'user')},
            },
        ),
    ]
