# Generated by Django 4.0.3 on 2022-05-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0013_remove_classmember_sequence_and_more'),
        ('yogas', '0022_favouriteasana'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaasanasequence',
            name='yoga_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='classcalendar.yogaclass'),
        ),
    ]
